plugins {
    id 'com.android.application'
}

android {
    namespace 'com.atuy.hoyogachahistory'
    compileSdk 35

    defaultConfig {
        applicationId 'com.atuy.hoyogachahistory'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '0.2.0'
    }

    buildFeatures {
        aidl true
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['META-INF/AL2.0', 'META-INF/LGPL2.1']
        }
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
